<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
    *{
      padding: 0;
      margin: 0;
    }
    </style>
    <title>Document</title>
</head>

<body>
<form action="/colab/submit" method="post">
  <select>
  <?php foreach($colab as $colabs) { ?>
    <option value=""><?=$colabs->ip?> | <?= $colabs->inserted?></option><br>
  <?php }?>
  </select><br>
      <textarea name="content" cols="20" rows="20"></textarea><br>
		<button type="submit">Submit</button>
	</form>
</body>

</html>